### ISSUE TITLE
Bikin Stage 🍕

### ISSUE THREAD

**Issue by jedediahfanuel** [Jeddi212/Arcadia#12]
Pilih 1 lagu aja bebas, terus copy aja scene yang **CobaCoba** si timothy, terus sinkronin si obstacle smaa lagunya.

- [x] Stage D
- [x] Stage E #28 
- [x] Stage J #30 
- [x] Stage T #40

**Comment by Jeddi212** [comment]
- [x] Stage J #30 
- [x] Stage E #28 
- [ ] Stage D
- [ ] Stage T
