### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by jedediahfanuel** [Jeddi212/Arcadia#13]
- Tampilan Score? (Jumlah Bensin yang kekumpul?)
- Tampilan Bensin
- 
Mungkin nyambung sama #20 dan #14 

- [x] Power Up

**Comment by jedediahfanuel** [comment]
Score Text Mesh Pro >> #21

**Comment by jedediahfanuel** [comment]
Fuel Bar >> #33

**Comment by Jeddi212** [comment]
- [ ] Power ups
